version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_DOCKER_PORT}:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/app:/app
    ports:
      - "${DOCKER_PORT}:${BACKEND_PORT}"
    environment:
      - HOST=${HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - RELOAD=${RELOAD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    command: bash -c "alembic upgrade head && python main.py"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
  